spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/esport_db
    username: postgres
    password: rin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # ? ?????? ?????????? ??? ??????. Hibernate ??? ??????? ??????? ?? ????? ???????.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # ???????? ??????????? SQL
    show-sql: true # ?????????? SQL ??????? ? ??????? (????? ??????? ??? ??????)

# ????????? ?????, ???? ????? (?? ????????? 8080)
server:
  port: 8080